AtropineEnjoyer/AtropineEnjoyer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('armory/', include('armory.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('', RedirectView.as_views(url='armory/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AtropineEnjoyer/armory/urls.py
from django.urls import path
from . import views
from django.conf import settings

urlpatterns = [
    path('', views.user_login, name='login'),
    path('login/', views.user_login, name='login'),
    path('signup/', views.user_signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
]

AtropineEnjoyer/catalog/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from armory.views import add_character
from django.views.decorators.cache import cache_page


router = routers.DefaultRouter()
router.register(r'combat-engravings', views.CombatEngravingViewSet)


urlpatterns = [
    path('', cache_page(60*60)(views.IndexArchetypeList.as_view()), name='archetype'),
    # path('character/', user_character_list, name='user-character-list'), replaced by IndexArchetypeList
    path('archetype/<int:pk>', cache_page(60*60)(views.ArchetypeDetailView.as_view()), name='archetype-detail'),
    path('class/', views.AllClassListView.as_view(), name='class'),
    path('class/<int:pk>', cache_page(60*60)(views.AllClassDetailView.as_view()), name='class-detail'),
    path('combat-engraving/', views.CombatEngravingListView.as_view(), name='combat-engraving'),
    path('combat-engraving/<int:pk>', views.CombatEngravingDetailView.as_view(), name='combat-engraving-detail'),
    path('class-engraving/', views.ClassEngravingListView.as_view(), name='class-engraving'),
    path('class-engraving/<int:pk>', views.ClassEngravingDetailView.as_view(), name='class-engraving-detail'),
    path('character/', views.CharacterList.as_view(), name='character'),
    path('character/<int:pk>', views.CharacterDetail.as_view(), name='character-detail'),
    path('combat-engravings-rest/', include(router.urls)),
    path('add-character', add_character, name='add-character'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AtropineEnjoyer/catalog/models.py
from django.dispatch import receiver
from django.urls import reverse
from django.db import models
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower
from django.conf import settings


class Character(models.Model):
    name = models.CharField(max_length=40, unique=True, help_text="Character name")
    the_class = models.ForeignKey('AllClass', on_delete=models.RESTRICT, null=True)
    ilv = models.IntegerField(default=0)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('character-detail', args=[str(self.id)])


class Archetype(models.Model):
    name = models.CharField(max_length=40, unique=True, help_text="Name of this archetype(e.g. Martial Artist)")

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('archetype-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class ClassEngraving(models.Model):
    name = models.CharField(max_length=40, unique=True)
    description = models.TextField(max_length=1000)
    associated_class = models.ForeignKey('AllClass', on_delete=models.RESTRICT, null=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('class-engraving-detail', args=[str(self.id)])


class AllClass(models.Model):
    name = models.CharField(max_length=40, unique=True, help_text="Name of this class(e.g. Wardancer)")
    archetype = models.ForeignKey('Archetype', on_delete=models.RESTRICT, null=True)
    icon = models.ImageField(upload_to='icons', default='media/default/default_icon.jpg')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('class-detail', args=[str(self.id)])

    class Meta:
        ordering = ['name']
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='genre_name_case_insensitive_unique',
                violation_error_message="Class already exists (case insensitive match)"
            ),
        ]


class CombatEngraving(models.Model):
    name = models.CharField(max_length=40, unique=True)
    description = models.TextField(max_length=1000, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('combat-engraving-detail', args=[str(self.id)])

AtropineEnjoyer/catalog/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from .models import CombatEngraving, ClassEngraving, AllClass, Archetype, Character
from django.views import generic
from .serializers import CharacterSerializer, CombatEngravingSerializer
from django.http import JsonResponse, HttpResponse, Http404
from rest_framework import permissions, viewsets, status
from rest_framework.parsers import JSONParser
from rest_framework.decorators import api_view
from rest_framework.views import APIView


class IndexArchetypeList(generic.ListView):
    model = Archetype
    paginate_by = 6
    context_object_name = 'archetype_list'
    template_name = 'index.html'


class CharacterList(APIView):
    permission_classes = [IsAuthenticated]
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(CharacterList, self).dispatch(request, *args, **kwargs)


    def get(self, request, format=None):
        character = Character.objects.filter(owner=request.user.id)
        serializer = CharacterSerializer(character, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = CharacterSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CharacterDetail(APIView):
    permission_classes = [IsAuthenticated]
    model = Character

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(CharacterDetail, self).dispatch(request, *args, **kwargs)

    def get_object(self, pk):
        try:
            return Character.objects.get(pk=pk)
        except Character.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        character = self.get_object(pk)
        serializer = CharacterSerializer(character)
        return Response(serializer.data,template_name='catalog/character_detail.html')

    def put(self, request, pk, format=None):
        character = self.get_object(pk)
        serializer = CharacterSerializer(character, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        character = self.get_object(pk)
        character.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


# replaced by IndexArchetypeList
# class ArchetypeListView(generic.ListView):
#     model = Archetype
#     paginate_by = 6
#     context_object_name = 'archetype_list'
#     template_name = 'index.html'


class ArchetypeDetailView(generic.DetailView):
    model = Archetype


class AllClassListView(generic.ListView):
    model = AllClass
    paginate_by = 10
    context_object_name = 'class_list'
    template_name = 'catalog/class_list.html'


class AllClassDetailView(generic.DetailView):
    model = AllClass

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        allclass = context['object']
        context['class'] = allclass

        return context


class CombatEngravingListView(generic.ListView):
    model = CombatEngraving
    paginate_by = 10
    context_object_name = 'combat_engraving_list'
    template_name = 'catalog/combat_engraving.html'


class CombatEngravingDetailView(generic.DetailView):
    model = CombatEngraving

    def get(self, request, *args, **kwargs):
        return self.combat_engraving_detail_view(request, *args, **kwargs)

    def combat_engraving_detail_view(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return render(request, 'catalog/combatengraving_detail.html', context={'combat_engraving': context['object']})


class ClassEngravingListView(generic.ListView):
    model = ClassEngraving
    paginate_by = 10
    context_object_name = 'class_engraving_list'
    template_name = 'catalog/class_engraving.html'


class ClassEngravingDetailView(generic.DetailView):
    model = ClassEngraving

    def get(self, request, *args, **kwargs):
        return self.class_engraving_detail_view(request, *args, **kwargs)

    def class_engraving_detail_view(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return render(request, 'catalog/classengraving_detail.html', context={'class_engraving': context['object']})


class CombatEngravingViewSet(viewsets.ModelViewSet):
    queryset = CombatEngraving.objects.all().order_by('name')
    serializer_class = CombatEngravingSerializer
    permission_classes = [permissions.IsAuthenticated]

AtropineEnjoyer/catalog/templates/catalog/allclass_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <img src="{{class.icon.url}}"/>
  <h1>{{ class.name }}</h1>

  <p><strong>Name:</strong> {{ class.name }}</p>
  <p><strong>Archetype:</strong> {{ class.archetype }}</p>
  <p><strong>Class Engraving:</strong>
    <br>
  {% for engraving in class.classengraving_set.all %}
    <span style="margin-left: 126px;">
    <a href="{% url 'class-engraving-detail' engraving.pk %}"> {{ engraving }}</a><br></span>
  {% endfor %}
  </p>
{% endblock %}

AtropineEnjoyer/catalog/templates/catalog/archetype_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ archetype.name }}</h1>

  <p>
    {% for archetype in archetype.allclass_set.all %}
    <br>
    <br>
      <span style="margin-left: 100px;"><a href="{% url 'class-detail' archetype.pk %}"> {{ archetype }}</a></span><br>
    {% endfor %}
  </p>

{% endblock %}

AtropineEnjoyer/catalog/templates/catalog/character_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ serializer.name }}</h1>
{% endblock %}

AtropineEnjoyer/catalog/templates/catalog/class_engraving.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Class Engraving List</h1>
  {% if class_engraving_list %}
    <ul>
      {% for class in class_engraving_list %}
      <li>
        <a href="{{ class.get_absolute_url }}">{{ class.name }}</a>
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no class engravings in Trixion.</p>
  {% endif %}
{% endblock %}

AtropineEnjoyer/catalog/templates/catalog/class_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Class List</h1>
  {% if class_list %}
    <ul>
      {% for class in class_list %}
      <li>
        <a href="{{ class.get_absolute_url }}">{{ class.name }}</a>
        &emsp;|{{class.archetype.name}}|
        &emsp;{{class.first_class_engraving}}&emsp;
        {{class.second_class_engraving}}
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no class in Trixion.</p>
  {% endif %}
{% endblock %}

AtropineEnjoyer/catalog/templates/catalog/classengraving_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ class_engraving.name }}</h1>
  <p><strong>Name:</strong> {{ class_engraving.name }}</p>
  <p><strong>Description:</strong> {{ class_engraving.description }}</p>
{% endblock %}

AtropineEnjoyer/catalog/templates/catalog/combat-engraving.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Combat Engraving List</h1>
  {% if combat_engraving_list %}
    <ul>
      {% for combat in combat_engraving_list %}
      <li>
        <a href="{{ combat.get_absolute_url }}">{{ combat.name }}</a>
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no combat engravings in Trixion.</p>
  {% endif %}
{% endblock %}

AtropineEnjoyer/catalog/templates/catalog/combat_engraving.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Combat Engraving List</h1>
  {% if combat_engraving_list %}
    <ul>
      {% for combat in combat_engraving_list %}
      <li>
        <a href="{{ combat.get_absolute_url }}">{{ combat.name }}</a>
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no combat engravings in Trixion.</p>
  {% endif %}
{% endblock %}

AtropineEnjoyer/catalog/templates/catalog/combatengraving_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ combat_engraving.name }}</h1>
  <p><strong>Name:</strong> {{ combat_engraving.name }}</p>
  <p><strong>Description:</strong> {{ combat_engraving.description }}</p>
{% endblock %}