AtropineEnjoyer/AtropineEnjoyer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('armory/', include('armory.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('', RedirectView.as_views(url='armory/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AtropineEnjoyer/armory/urls.py
from django.urls import path
from . import views
from django.conf import settings

urlpatterns = [
    path('', views.user_login, name='login'),
    path('login/', views.user_login, name='login'),
    path('signup/', views.user_signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
]

AtropineEnjoyer/armory/models.py
from django.db import models

# Create your models here.

AtropineEnjoyer/catalog/models.py
from django.dispatch import receiver
from django.urls import reverse
from django.db import models
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower
from django.conf import settings


class Character(models.Model):
    name = models.CharField(max_length=40, unique=True, help_text="Character name")
    the_class = models.ForeignKey('AllClass', on_delete=models.RESTRICT, null=True)
    ilv = models.IntegerField(default=0)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('character-detail', args=[str(self.id)])


class Archetype(models.Model):
    name = models.CharField(max_length=40, unique=True, help_text="Name of this archetype(e.g. Martial Artist)")

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('archetype-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class ClassEngraving(models.Model):
    name = models.CharField(max_length=40, unique=True)
    description = models.TextField(max_length=1000)
    associated_class = models.ForeignKey('AllClass', on_delete=models.RESTRICT, null=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('class-engraving-detail', args=[str(self.id)])


class AllClass(models.Model):
    name = models.CharField(max_length=40, unique=True, help_text="Name of this class(e.g. Wardancer)")
    archetype = models.ForeignKey('Archetype', on_delete=models.RESTRICT, null=True)
    icon = models.ImageField(upload_to='icons', default='media/default/default_icon.jpg')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('class-detail', args=[str(self.id)])

    class Meta:
        ordering = ['name']
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='genre_name_case_insensitive_unique',
                violation_error_message="Class already exists (case insensitive match)"
            ),
        ]


class CombatEngraving(models.Model):
    name = models.CharField(max_length=40, unique=True)
    description = models.TextField(max_length=1000, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('combat-engraving-detail', args=[str(self.id)])

AtropineEnjoyer/armory/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

AtropineEnjoyer/armory/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import SignupForm, LoginForm
from catalog.models import Character, AllClass
from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework_simplejwt.exceptions import TokenError
from rest_framework_simplejwt.tokens import AccessToken
from rest_framework_simplejwt.authentication import JWTAuthentication
JWT_authenticator = JWTAuthentication()

def user_login(request):
    if request.method == 'POST':
        access_token = request.headers.get('Authorization')
        print(access_token)
        if access_token:
            try:
                print(111)
                # Validate the access token
                access_token_obj = JWT_authenticator.authenticate(request)
                print(222)
                if access_token_obj is not None:
                    # unpacking
                    user, token = access_token_obj
                    print(user)
                    print(token.payload)
                if user is not None:
                    # If the access token is valid, log in the user
                    login(request, user)
                    return JsonResponse({'message': 'Login successful'})
                else:
                    return JsonResponse({'error': 'Invalid access token'}, status=400)
            except TokenError:
                return JsonResponse({'error': 'Invalid access token'}, status=400)

        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                refresh = RefreshToken.for_user(user)

                return JsonResponse(
                    {
                        'refresh': str(refresh),
                        'access': str(refresh.access_token)
                    }
                )
                # return redirect('archetype')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})


def user_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('login')

# replaced by IndexArchetypeList
# def user_character_list(request):
#     if request.user.is_authenticated:
#         character_list = Character.objects.filter(owner=request.user.id)
#         return render(request, 'add_character.html', context={'character_list': character_list})
#     else:
#         return 0


def add_character(request):
    all_classes = AllClass.objects.all()
    return render(request, 'add_character.html', {'all_classes': all_classes})

AtropineEnjoyer/armory/templates/add_character.html
{% extends 'base_generic.html' %}

{% block content %}
    <form action="character/" method="post">
        {% csrf_token %}
        <label for="id_name">Name:</label>
        <input type="text" id="id_name" name="name">
        <br>
        <label for="id_the_class">Choose a Class:</label>
        <select name="the_class" id="id_the_class">
            {% for class_instance in all_classes %}
                <option value="{{ class_instance.pk }}">{{ class_instance.name }}</option>
            {% endfor %}
        </select>
        <br>
        <label for="id_ilv">Item Level:</label>
        <input type="number" id="id_ilv" name="ilv">
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

AtropineEnjoyer/armory/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 85vh;
            margin: 0;
            background-image: url('../../media/backgounds/login_bg.jpg');
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }

        .form-container {
            background-color: rgba(255, 255, 255, 0.3);
            padding: 30px;
            border-radius: 5px;
            text-align: center;
            box-shadow: 0 0 20px 10px rgba(255, 255, 255, 0.3);
        }
    </style>
</head>
<body>
    <div class="form-container">
        <p style="font-size: 5em;"><strong>LOAPedia</strong></p>
        <h1 style="text-align: center;">Login</h1>

        {% if error %}
        <p>{{ error }}</p>
        {% endif %}

        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div style="text-align: center;">
                <button type="submit">Login</button>
                <a href="{% url 'signup' %}">Don't have Account? Create</a>
            </div>
        </form>
    </div>
</body>
</html>

AtropineEnjoyer/armory/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Signup</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 85vh;
            margin: 0;
            background-image: url('../../media/backgounds/login_bg.jpg');
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }

        .form-container {
            background-color: rgba(255, 255, 255, 0.3);
            padding: 30px;
            border-radius: 5px;
            text-align: left;
            box-shadow: 0 0 20px 10px rgba(255, 255, 255, 0.3);
        }
    </style>
</head>
<body>
    <div class="form-container">
        <p style="font-size: 5em; text-align: center;"><strong>LOAPedia</strong></p>
        <h1 style="text-align: center;">Signup</h1>

        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div style="text-align: center;">
            <button type="submit">Signup</button>
            <a href="{% url 'login' %}">Already have an account?</a>
            </div>
        </form>
    </div>
</body>
</html>